#!/usr/bin/env python
"""
This converts reST-formatted .txt files into .html files.

This assumes you have docutils installed on your system.
"""
import os, sys

def buildhtml():
    if os.system("rst2html.py --version") != 0:
        print "I can't seem to find rst2html.  Try installing it "
        print "or adding the directory to your path."
        print "Exiting."
        sys.exit(1)

    newdir = os.getcwd()

    files = os.listdir(os.getcwd())
    files = [ f for f in files if f.endswith(".txt") ]

    for mem in files:
        print "building %s" % mem
        htmlfn = os.path.join(newdir, "%s.html" % mem[:-4])
        mwfn = os.path.join(newdir, "%s.mw" % mem[:-4])

        os.system("rst2html.py %s %s" % (mem, htmlfn))
        os.system("html2wiki --dialect MediaWiki %s > %s" % (htmlfn, mwfn))

if __name__ == "__main__":
    buildhtml()
